steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--no-cache", "--quiet"]

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "--- DEBUG: Starter oprydningstrin ---"

        echo "DEBUG: Henter versioner der skal slettes (alle undtagen den nyeste)..."
        # Sorterer med nyeste først (--sort-by '~version').
        # --format 'value(VERSION.ID)' giver kun version ID'er.
        # 'tail -n +2' springer den første linje (den nyeste version) over.
        versions_to_delete=$(gcloud app versions list \
            --service default \
            --project "$PROJECT_ID" \
            --sort-by '~version' \
            --format 'value(VERSION.ID)' | tail -n +2)

        if [ -z "$versions_to_delete" ]; then
          echo "DEBUG: Ingen gamle versioner fundet til sletning."
        else
          echo "DEBUG: Følgende versioner vil blive forsøgt slettet:"
          echo "$versions_to_delete"
          # Nedenstående linje udfører selve sletningen.
          # -r optionen til xargs forhindrer kørsel hvis $versions_to_delete er tom.
          echo "$versions_to_delete" | xargs -r -I {} gcloud app versions delete {} --service default --project "$PROJECT_ID" --quiet
          echo "DEBUG: Sletning af gamle versioner forsøgt."
        fi
        echo "--- DEBUG: Oprydningstrin afsluttet ---"

options:
  logging: CLOUD_LOGGING_ONLY